### ISSUE TITLE
issue with GATK wdls

### ISSUE THREAD

**Issue by ahdee** [dnanexus/dxCompiler#148]
Hi, I'm trying to compile the wdl from the GATK workflow, 
https://dockstore.org/workflows/github.com/broadinstitute/gatk/mutect2:4.1.8.1?tab=info

however running a few versions including the latest yields this error here: 

```
java -jar dxCompiler-2.4.7.jar compile /dnanexus/workflows/gatk/mutect2.wdl -project WES -folder /workflows/mutec2
[error] WDL code is syntactically valid BUT it fails type-checking -----
version 1.0

```
Is this something on my end or is this just not formatted correctly. Interestingly the link has a import to dnanexus button above. 

A

**Comment by jdidion** [comment]
Hi there - unfortunately that WDL contains several bugs. You can see a full list of the issues by using `https://github.com/dnanexus-rnd/wdlTools` `check` command, e.g. `java -jar wdlTools.jar check ~/Downloads/scripts/mutect2_wdl/mutect2.wdl`. A few of the issues can be fixed automatically by running the `fix` command, but the others you'll have to fix manually.

Unfortunately Cromwell will happily run a WDL file with errors in it, which can lead to runtime errors (i.e. rather than catching the error right away and reporting it, it will run your workflow for several hours before it crashes) or even give you unexpected results. `dxCompiler` adheres strictly to the WDL spec and will not run a WDL that contains errors that we are able to detect at compile time.

**Comment by jdidion** [comment]
The issues are:
* At line 190, an `object` keyword is required before the literal value (i.e. `Runtime runtime = object { ... }`
* At lines 440 and 550, `select_first` must be called on the optional value
* At line 1093, the `sep` option must be used with an array; `transcript_selection_list` is of type `File?`

The other issues can be fixed automatically by the `fix` command

**Comment by ahdee** [comment]
@jdidion thank you for that. Its surprising to see so many errors coming from a GATK acrhived workflow.
