### ISSUE TITLE
WDL tasks in docker containers are missing DX environment variables

### ISSUE THREAD

**Issue by ANickerson** [dnanexus/dxCompiler#453]
Hello,

I was creating a wdl that would access files directly from dnanexus something similar to:
```{wdl}
task test{
   comand<<<
   python3 -c "import dxpy; list(dxpy.find_jobs())"
   >>>
    runtime{
        docker: "dockerimage"
        dx_access: object{
            Project: "CONTRIBUTE"
        }
    }
}
```

But the command fails with a permission error:
"Requires VIEW access to the project".

On further investigation adding `source /home/dnanexus/environment` to the command section  does seem to work.

I suspect adding this to the `commandScript` file or in `containerRunScript` would solve the problem.

**Comment by Gvaihir** [comment]
At the moment, due to the security implications we do not recommend exposing your tokens to the container environment. I can not attest whether this will change soon to consider exposing application execution environment to the container and make it a default behavior. Maybe our product team may evaluate.
